---
title: "Assignment 05"
output: html_document
date: "2023-01-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# load packages

rm(list = ls())

library(jsonlite)
library(httr)
library(rlist)
library(tidyverse)
library(ggplot2)
library(maps)

```


### Ecercise 4
https://github.com/ltyita/R_Assign05.git

```{r}

# Exercise (6) import api key
source("ticket_APIkey.R")

```


### Ecercise 7

```{r}

# Exercise (7)
# first GET request that searches for event venues in Germany
API_DE <- GET("https://app.ticketmaster.com/discovery/v2/venues.json?",
                   query = list("countryCode" = "DE",
                                "apikey" = api_key)) 

# extract content
API_decontent <- content(API_DE)

# number of page and observation
n <- as.data.frame(API_decontent[["page"]])



```

From data frame, it suggests that each page contains 20 observations, and there are `r n$Elements` events in Germany, which make them `r n$totalPages`-page long. And we are currently at page 0.



### Exercise 8

```{r}

# Exercise (8)
# make the first 20 obs as a data frame that contains name, the city, the postalCode and address, 
# as well as the url and the longitude and latitude. 

# create an empty data frame dim: 20X7
de_venues <- data.frame(matrix(NA, nrow = 20, ncol = 7))
colnames(de_venues) <- c("name", "city", "postalCode", "address", 
                         "url", "longitude", "latitude")


for (i in 1:20){
  de_venues[i,] <- c(ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$name), 
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$name),
                     ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$city$name),
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$city$name),
                     ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$postalCode),
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$postalCode),
                     ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$address$line1),
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$address$line1),
                     ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$url),
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$url),
                     ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$location$longitude),
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$location$longitude),
                     ifelse(is.null(API_decontent$`_embedded`["venues"][[1]][[i]]$location$latitude),
                            NA, API_decontent$`_embedded`["venues"][[1]][[i]]$location$latitude))
}

```


```{r}

# Exercise (9) iterate every page


venue_page <- function(page, country_name){
  Sys.sleep(.3)
  API_DE_page <- GET("https://app.ticketmaster.com/discovery/v2/venues.json?",
                query = list("page" = page,
                             "countryCode" = country_name,
                             "apikey" = api_key)) 
  content_page <- content(API_DE_page)
  
  test_page <- content_page$page$totalPages
  
  # while loop to prevent the error occurred (make sure the positive value of test_page)
  while (is.null(test_page)){
    API_DE_page <- NULL
    API_DE_page <- GET("https://app.ticketmaster.com/discovery/v2/venues.json?",
                       query = list("page" = page,
                                    "countryCode" = "DE",
                                    "apikey" = api_key))
    content_page <- NULL
    content_page <- content(API_DE_page)
    test_page <- content_page$page$totalPages
  }
  test_page <- (test_page - 1)
  # no. of obs in each page
  k <- length(content_page$`_embedded`[["venues"]]) %>% as.numeric()
  
  # only the last page that gets value less than 20 obs.
  m <- ifelse(page == test_page, k, 20) %>% as.numeric()

  # create an empty data frame
  test1 <- data.frame()
  
  # loop trough the obs. in each page
  for (i in 1:m){
    test1 <- test1 %>% rbind(c(ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$name),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$name),
                               ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$city$name),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$city$name),
                               ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$postalCode),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$postalCode),
                               ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$address$line1),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$address$line1),
                               ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$url),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$url),
                               ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$location$longitude),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$location$longitude),
                               ifelse(is.null(content_page$`_embedded`["venues"][[1]][[i]]$location$latitude),
                                      NA, content_page$`_embedded`["venues"][[1]][[i]]$location$latitude)))
  }
  # change col. names
  colnames(test1) <- c("name", "city", "postalCode", "address", 
                           "url", "longitude", "latitude")
  #API_DE_page <- NULL
  return(test1)
}


```
